/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniprjct;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Hariprasad
 */
public class Match_Insert extends javax.swing.JFrame {

    /**
     * Creates new form Match_Insert
     */
    public Match_Insert() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.jpeg")));
        ConfigureFrame.ConfigureFrame(this,"Match Insert",1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        winner = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        team1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        team2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        venue = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        match = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Enter Winner");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(970, 400, 258, 44);

        winner.setBackground(new java.awt.Color(255, 153, 153));
        winner.setFont(new java.awt.Font("Tahoma", 3, 23)); // NOI18N
        winner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(winner);
        winner.setBounds(1110, 470, 360, 35);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Enter Team 1");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(183, 207, 252, 53);

        team1.setBackground(new java.awt.Color(255, 153, 153));
        team1.setFont(new java.awt.Font("Tahoma", 3, 23)); // NOI18N
        team1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(team1);
        team1.setBounds(342, 273, 360, 35);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Enter Team 2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(183, 355, 263, 47);

        team2.setBackground(new java.awt.Color(255, 153, 153));
        team2.setFont(new java.awt.Font("Tahoma", 3, 23)); // NOI18N
        team2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(team2);
        team2.setBounds(342, 415, 360, 35);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Enter Venue");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 490, 310, 41);

        venue.setBackground(new java.awt.Color(255, 153, 153));
        venue.setFont(new java.awt.Font("Tahoma", 3, 23)); // NOI18N
        venue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(venue);
        venue.setBounds(342, 550, 360, 35);

        add.setBackground(new java.awt.Color(255, 255, 0));
        add.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        add.setText("Save");
        add.setBorder(new javax.swing.border.MatteBorder(null));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add);
        add.setBounds(950, 590, 112, 51);

        cancel.setBackground(new java.awt.Color(255, 255, 0));
        cancel.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        cancel.setText("Cancel");
        cancel.setBorder(new javax.swing.border.MatteBorder(null));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel);
        cancel.setBounds(1330, 590, 109, 51);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Enter the Match Number");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(183, 64, 270, 44);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Enter Time");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(970, 90, 258, 44);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Enter Date");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(970, 240, 258, 44);

        match.setBackground(new java.awt.Color(255, 153, 153));
        match.setFont(new java.awt.Font("Tahoma", 3, 23)); // NOI18N
        match.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(match);
        match.setBounds(342, 121, 360, 35);

        time.setBackground(new java.awt.Color(255, 153, 153));
        time.setFont(new java.awt.Font("Tahoma", 3, 23)); // NOI18N
        time.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(time);
        time.setBounds(1100, 150, 360, 35);

        date.setBackground(new java.awt.Color(255, 153, 153));
        date.setFont(new java.awt.Font("Tahoma", 3, 23)); // NOI18N
        date.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(date);
        date.setBounds(1110, 310, 360, 35);

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\Cricket\\samarth-shirke-ghxL3qOfkPo-unsplash.jpeg")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(-60, -30, 1980, 1080);

        jMenu2.setText("More");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Back");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setText("Logout");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1053, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1053, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        /*if (add.getText().equals("Add")){
            winner.setText("");
            team1.setText("");
            team2.setText("");
            venue.setText("");
            match.setText("");
            time.setText("");
            date.setText("");
            winner.setEditable(true);
            team1.setEditable(true);
            team2.setEditable(true);
            venue.setEditable(true);
            match.setEditable(true);
            time.setEditable(true);
            date.setEditable(true);
            add.setText("Save");
        }
        else{*/
            if( !winner.getText().equals("") && !team1.getText().equals("") && !team2.getText().equals("") && !venue.getText().equals("") && !match.getText().equals("") && !time.getText().equals("") && !date.getText().equals("")){
                String SQL="INSERT INTO MATCHES VALUES ("+Integer.parseInt(match.getText().trim())+",'"+team1.getText().trim()+"','"+team2.getText().trim()+"','"+venue.getText().trim()+"','"+date.getText().trim()+"','"+time.getText().trim()+"','"+winner.getText().trim()+"')";
                int retVal=Operation.UPDATE_Table(SQL);
                if(retVal==-1){
                    JOptionPane.showMessageDialog(this, "Operation Failed", "Match insertion..", 1);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Operation successfully completed", "Match insertion..", 1);
                }
                winner.setText("");
                team1.setText("");
                team2.setText("");
                venue.setText("");
                match.setText("");
                time.setText("");
                date.setText("");
               // add.setText("Add");
                winner.setEditable(false);
                team1.setEditable(false);
                team2.setEditable(false);
                venue.setEditable(false);
                match.setEditable(false);
                time.setEditable(false);
                date.setEditable(false);
            }
    }//GEN-LAST:event_addActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
       Match.main(null);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Match.main(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Signup.main(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Match_Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Match_Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Match_Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Match_Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Match_Insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField match;
    private javax.swing.JTextField team1;
    private javax.swing.JTextField team2;
    private javax.swing.JTextField time;
    private javax.swing.JTextField venue;
    private javax.swing.JTextField winner;
    // End of variables declaration//GEN-END:variables
}
